name: Pipiline CI Padrão


on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-e-testes:
    runs-on: ubuntu-latest 

    steps:
    
    - name: Checkout do código
      uses: actions/checkout@v4

    
    - name: Configurar o Java (JDK 17)
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin' 
        cache: maven 

    
    - name:  Build e Testes com Maven
      run: mvn clean verify